### ISSUE TITLE
Convexity map plot throws exception

### ISSUE THREAD

**Issue by CellDynamics** [CellDynamics/QuimP#310]
Perhaps it happens when fluo maps are not available,

**Comment by CellDynamics** [comment]
```
32-Warning! Colour out of range:                                                                                                                                                                                                                                               R:1.0 G: Infinity B: 0.0                                                                                                                      
java.lang.Exception                                                                                                                                                                 
        at com.github.celldynamics.quimp.QColor.setRGB(QColor.java:143)                                                                                                                                                                                                                at com.github.celldynamics.quimp.QColor.<init>(QColor.java:56)                                                                                                                                                                                                                 at com.github.celldynamics.quimp.QColor.rbbMap(QColor.java:350)                                                                                                                                                                                                                at com.github.celldynamics.quimp.QColor.erColorMap2(QColor.java:268)                                                                                                                                                                                                           at com.github.celldynamics.quimp.plugin.qanalysis.STmap.map2ColorImagePlus(STmap.java:683)                                                                                                                                                                                     at com.github.celldynamics.quimp.plugin.protanalysis.ActionPlotMap.actionPerformed(ActionPlotMap.java:78) 
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)                                                                                                                                                                                            
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)                                                                                                                                                                                        
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)                                                                                                                                                                                     
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)           
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)                                                                                                                                                                                            
        at java.awt.Component.processMouseEvent(Component.java:6541)                 
```

**Comment by CellDynamics** [comment]
To reproduce:

1. Have full QCONF (with ANA and Q)
2. Recompute only ECMM
3. Try to show CONV map from PA - will fail because #129

**Comment by CellDynamics** [comment]
This is due to invalid Q-Analysis after re-running ECMM
